### ISSUE TITLE
does not compile

### ISSUE THREAD

**Issue by ghost** [Coding-Badly/TinyISP#1]
Downloaded, opened, hit verify; fail.
What am I doing wrong?

```
/tmp/cch4AupX.ltrans1.ltrans.o: In function `L1500bsayhello':
cch4AupX.ltrans1.o:(.text+0x9ca): undefined reference to `knb_ring_space'
cch4AupX.ltrans1.o:(.text+0x9ce): undefined reference to `knb_ring_head'
/tmp/cch4AupX.ltrans1.ltrans.o: In function `L1500bfault':
cch4AupX.ltrans1.o:(.text+0xabc): undefined reference to `kbr_fault_code'
cch4AupX.ltrans1.o:(.text+0xac4): undefined reference to `kbr_fault_code'
/tmp/cch4AupX.ltrans1.ltrans.o: In function `L1500bfaultnoidle':
cch4AupX.ltrans1.o:(.text+0xada): undefined reference to `kbr_fault_code'
cch4AupX.ltrans1.o:(.text+0xae2): undefined reference to `kbr_fault_code'
/tmp/cch4AupX.ltrans1.ltrans.o: In function `L1500bcommit':
cch4AupX.ltrans1.o:(.text+0xaea): undefined reference to `knb_ring_space'
cch4AupX.ltrans1.o:(.text+0xaee): undefined reference to `knb_ring_head'
collect2: error: ld returned 1 exit status
exit status 1
Error compiling for board Arduino Pro or Pro Mini.
```

**Comment by Coding-Badly** [comment]
Worked for me (IDE version 1.6.9).

**Comment by etatto** [comment]
I have the same issue with the latest version of the Arduino IDE (1.6.12 with 1.6.14 of the AVR boards defs)
`C:\Users\eto\AppData\Local\Temp\cc1iVyTr.ltrans1.ltrans.o: In function`L1520bsayhello':
cc1iVyTr.ltrans1.o:(.text+0x9ee): undefined reference to `knb_ring_space'
cc1iVyTr.ltrans1.o:(.text+0x9f2): undefined reference to`knb_ring_head'
C:\Users\eto\AppData\Local\Temp\cc1iVyTr.ltrans1.ltrans.o: In function `L1520bfault':
cc1iVyTr.ltrans1.o:(.text+0xae0): undefined reference to`kbr_fault_code'
cc1iVyTr.ltrans1.o:(.text+0xae8): undefined reference to `kbr_fault_code'
C:\Users\eto\AppData\Local\Temp\cc1iVyTr.ltrans1.ltrans.o: In function`L1520bfaultnoidle':
cc1iVyTr.ltrans1.o:(.text+0xafe): undefined reference to `kbr_fault_code'
cc1iVyTr.ltrans1.o:(.text+0xb06): undefined reference to`kbr_fault_code'
C:\Users\eto\AppData\Local\Temp\cc1iVyTr.ltrans1.ltrans.o: In function `L1520bcommit':
cc1iVyTr.ltrans1.o:(.text+0xb0e): undefined reference to`knb_ring_space'
cc1iVyTr.ltrans1.o:(.text+0xb12): undefined reference to `knb_ring_head'`

I tested other versions and I think the 1.6.9 (with 1.6.11 AVR boards defs) is the last version to compile the TinyISP sketch.

**Comment by per1234** [comment]
Fixed by https://github.com/Coding-Badly/TinyISP/commit/c65845f3ca741a74adb96080a30f1bbe66ddce63
